routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Blog Controller Routes
Route::get('blog/{slug}', ['as' => 'blog.single', 'uses' => 'BlogController@getSingle']) -> where('slug', '[\w\d\-\_]+');

Route::get('blog', ['uses' => 'BlogController@getIndex', 'as' => 'blog.index']);


// Pages Controller Routes
Route::get('contact','PagesController@getContact' );

Route::post('contact', 'PagesController@postContact');

Route::get('about', 'PagesController@getAbout');

Route::get('/', 'PagesController@getIndex');


/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('categories', 'CategoryController', ['except' => ['create'] ]);

Route::resource('posts', 'PostController');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $table = 'categories';

    public function posts()
    {
    	return $this->hasMany('App\Post');
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
Use App\Category;
use Session;

class CategoryController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //display all the categories & a form to create new category.

        $categories = Category::all();
        return view('categories.index')->withCategories($categories);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Save a new categoy & redirect to index
        $this-> validate($request, ['name' => 'required|max:255']);
        $category = new Category;
        $category->name = $request->name;
        $category->save();

        Session::flash('success', 'New Category created successfully'); 

        return redirect()->route('categories.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/categories/index.blade.php
@extends('main')

@section('title', '| All Categories')

@section('content')

<div class="row">
	<div class="col-md-8">
		<h1>Categories</h1>
			<table class="table">
				<thead>
					<tr>
						<th>#</th>
						<th>Name</th>
					</tr>
				</thead>

				<tbody>
					@foreach ($categories as $category)
					<tr>
						<th>{{ $category -> id}}</th>
						<td>{{ $category -> name }}</td>
					</tr>
					@endforeach   
				</tbody>
			</table>
		</h1>
	</div><!--end of .col-md-8 -->

	<div class="col-md-3 col-md-offset-1">
		<div class="panel panel-info" style="position: fixed;margin-top: 50px; margin-left: 30px; text-align: center; border:2px dashed lightblue;">
			<div class="panel-heading">
				Create a Category
			</div>
			
			<div class="panel-body">
				<form action="{{ route('categories.store') }}" method="POST">
					{{csrf_field()}}
					
					<label class="form-spacing-top" style="text-align: left;"> Category Name:
					<input type="text" name="name" placeholder="category name please" class="form-control" style="margin-top: 8px;"></label>

					<input type="submit" value="Create New Category" class="btn btn-success form-spacing-top btn-block">

				</form>
			</div>

		</div>
	</div>

</div>

@stop